using System.Net;
using System.Text;
using ToroSquad.Modules.Updates.Domain;

namespace ToroSquad.Modules.Updates.Providers;

public abstract record ForumBlock;

public sealed record ForumHeading(string Text) : ForumBlock;

/// <param name="Emphasized">All of the text is bold — how a forum post writes a section title without a heading.</param>
public sealed record ForumParagraph(string Text, bool Emphasized) : ForumBlock;

public sealed record ForumList(IReadOnlyList<ForumListItem> Items) : ForumBlock;

/// <param name="Text">The item's own text, without its nested lists.</param>
public sealed record ForumListItem(string Text, bool Emphasized, IReadOnlyList<ForumListItem> Children);

/// <summary>
/// Reads the rendered HTML of a forum post ("cooked", generated by the forum from Markdown) into the few blocks an update
/// post is made of: headings, paragraphs and nested lists, as plain text. A small forward scanner, not a general HTML
/// parser and not a pattern match over markup: tags are recognized by name, everything unknown is transparent, quotes and
/// embeds (aside, blockquote, pre, table, script, style, svg) are left out, entities are decoded. Nothing is fetched — an
/// image or a link is only its text. Bounded in input size, list depth, item count and text length, and it never throws
/// on malformed markup: what cannot be read is skipped.
/// </summary>
public static class ForumHtml
{
    public const int MaxInputLength = 400_000;
    public const int MaxListDepth = 8;
    public const int MaxListItems = 3000;
    public const int MaxTextLength = 2000;
    private const int MaxTagLength = 4000;

    private static readonly HashSet<string> Ignored = new(StringComparer.Ordinal) { "aside", "blockquote", "pre", "table", "script", "style", "svg" };

    public static IReadOnlyList<ForumBlock> Read(string? html)
    {
        var builder = new Builder();
        if (string.IsNullOrEmpty(html))
            return builder.Finish();
        var end = Math.Min(html.Length, MaxInputLength);
        var i = 0;
        while (i < end)
        {
            if (html[i] == '<' && TryReadTag(html, i, end, out var name, out var closing, out var after))
            {
                builder.Tag(name, closing);
                i = after;
                continue;
            }

            var next = html.IndexOf('<', i + 1, end - i - 1);
            if (next < 0)
                next = end;
            builder.Text(WebUtility.HtmlDecode(html[i..next]));
            i = next;
        }

        return builder.Finish();
    }

    /// <summary>
    /// A tag or comment starting at <paramref name="start"/>: its lower-case name ("" for comments and declarations), whether
    /// it closes, and the index after it. False when the '<' is just text (no name follows, or the tag never ends).
    /// </summary>
    private static bool TryReadTag(string html, int start, int end, out string name, out bool closing, out int after)
    {
        name = "";
        closing = false;
        after = start + 1;
        if (start + 1 >= end)
            return false;
        if (html.AsSpan(start, Math.Min(4, end - start)).SequenceEqual("<!--"))
        {
            var close = html.IndexOf("-->", start + 4, StringComparison.Ordinal);
            after = close < 0 || close + 3 > end ? end : close + 3;
            return true;
        }

        var i = start + 1;
        if (html[i] == '/')
        {
            closing = true;
            i++;
        }

        var nameStart = i;
        while (i < end && char.IsAsciiLetterOrDigit(html[i]))
            i++;
        if (i == nameStart && (closing || html[nameStart] != '!'))
            return false;
        name = html[nameStart..i].ToLowerInvariant();

        var quote = '\0';
        var limit = Math.Min(end, start + MaxTagLength);
        for (; i < limit; i++)
        {
            var ch = html[i];
            if (quote != '\0')
            {
                if (ch == quote)
                    quote = '\0';
            }
            else if (ch is '"' or '\'')
            {
                quote = ch;
            }
            else if (ch == '>')
            {
                after = i + 1;
                return true;
            }
        }

        return false;
    }

    private sealed class Run
    {
        private readonly StringBuilder _text = new();
        private int _visible;
        private int _bold;

        public void Append(string text, bool bold)
        {
            foreach (var ch in text)
            {
                if (_text.Length >= MaxTextLength)
                    return;
                _text.Append(ch);
                if (char.IsWhiteSpace(ch) || char.IsControl(ch))
                    continue;
                _visible++;
                if (bold)
                    _bold++;
            }
        }

        public string Text => UpdateText.OneLine(_text.ToString());

        public bool Emphasized => _visible > 0 && _bold == _visible;
    }

    private sealed class Item
    {
        public Run Text { get; } = new();

        public List<Item> Children { get; } = [];

        public ForumListItem Build() => new(Text.Text, Text.Emphasized, Children.Select(c => c.Build()).Where(c => c.Text.Length > 0 || c.Children.Count > 0).ToList());
    }

    private sealed class Builder
    {
        private readonly List<ForumBlock> _blocks = [];
        private readonly Stack<List<Item>> _lists = new();
        private Run? _heading;
        private Run? _paragraph;
        private int _bold;
        private int _ignored;
        private int _items;

        public void Tag(string name, bool closing)
        {
            if (_ignored > 0)
            {
                // Inside something that is left out: only its own nesting is followed.
                if (Ignored.Contains(name) || name is "ul" or "ol")
                    _ignored += closing ? -1 : 1;
                return;
            }

            switch (name)
            {
                case "h1" or "h2" or "h3" or "h4" or "h5" or "h6":
                    if (closing)
                        EndHeading();
                    else
                    {
                        EndParagraph();
                        _heading = new Run();
                    }

                    break;
                case "p":
                    if (_lists.Count > 0)
                        Text(" ");
                    else if (closing)
                        EndParagraph();
                    else
                    {
                        EndParagraph();
                        _paragraph = new Run();
                    }

                    break;
                case "ul" or "ol":
                    if (closing)
                        EndList();
                    else if (_lists.Count >= MaxListDepth)
                        _ignored = 1;
                    else
                    {
                        EndParagraph();
                        _lists.Push([]);
                    }

                    break;
                case "li":
                    if (!closing && _lists.Count > 0 && _items < MaxListItems)
                    {
                        _lists.Peek().Add(new Item());
                        _items++;
                    }

                    break;
                case "strong" or "b":
                    _bold = Math.Max(0, _bold + (closing ? -1 : 1));
                    break;
                case "br":
                    Text(" ");
                    break;
                default:
                    if (!closing && Ignored.Contains(name))
                        _ignored = 1;
                    break;
            }
        }

        public void Text(string text)
        {
            if (_ignored > 0 || text.Length == 0)
                return;
            if (_heading is not null)
            {
                _heading.Append(text, _bold > 0);
                return;
            }

            if (_lists.Count > 0)
            {
                // Text before the first item of a list has no place; text in an item is that item's own text.
                if (_lists.Peek() is [.., var item])
                    item.Text.Append(text, _bold > 0);
                return;
            }

            if (_paragraph is null && string.IsNullOrWhiteSpace(text))
                return;
            (_paragraph ??= new Run()).Append(text, _bold > 0);
        }

        public IReadOnlyList<ForumBlock> Finish()
        {
            EndHeading();
            EndParagraph();
            while (_lists.Count > 0)
                EndList();
            return _blocks;
        }

        private void EndHeading()
        {
            if (_heading?.Text is { Length: > 0 } text)
                _blocks.Add(new ForumHeading(text));
            _heading = null;
        }

        private void EndParagraph()
        {
            if (_paragraph?.Text is { Length: > 0 } text)
                _blocks.Add(new ForumParagraph(text, _paragraph.Emphasized));
            _paragraph = null;
        }

        private void EndList()
        {
            if (_lists.Count == 0)
                return;
            var items = _lists.Pop();
            if (_lists.Count == 0)
            {
                var built = items.Select(i => i.Build()).Where(i => i.Text.Length > 0 || i.Children.Count > 0).ToList();
                if (built.Count > 0)
                    _blocks.Add(new ForumList(built));
                return;
            }

            // A nested list belongs to the item it was opened in (or to a nameless one when the markup had none).
            var parent = _lists.Peek();
            if (parent.Count == 0)
                parent.Add(new Item());
            parent[^1].Children.AddRange(items);
        }
    }
}
