using Microsoft.Extensions.DependencyInjection;
using ToroSquad.Discord.Commands.Manifest;
using ToroSquad.Discord.Interactions;
using ToroSquad.Tests.Support;

namespace ToroSquad.Tests.Unit;

/// <summary>Criteria 1, 4 and 15: real slash schema, separated permission groups, safe sync.</summary>
public sealed class CommandManifestTests
{
    private static async Task<(CommandManifest Manifest, IReadOnlySet<string> Admin)> BuildAsync(bool withExample = false)
    {
        await using var host = await TestHost.CreateAsync(new() { ["Modules:Example:Enabled"] = withExample ? "true" : "false" });
        var interactions = host.Services.GetRequiredService<InteractionHost>();
        var manifest = await interactions.InitializeAsync(host.Services);
        return (manifest, interactions.AdminCommandNames);
    }

    [Fact]
    public async Task Production_manifest_is_valid_and_contains_exactly_the_specified_commands()
    {
        var (manifest, admin) = await BuildAsync();
        CommandManifestValidator.Validate(manifest, admin).Should().BeEmpty();
        manifest.LoadErrors.Should().BeEmpty();
        manifest.Commands.Select(c => c.Name).Should().BeEquivalentTo("help", "bot", "privacy", "setup", "modules", "esports", "esports-admin");

        string[] Sub(string name) => manifest.Find(name)!.Options.Select(o => o.Name).ToArray();
        Sub("bot").Should().BeEquivalentTo("status", "about", "source");
        Sub("privacy").Should().BeEquivalentTo("export", "delete");
        Sub("modules").Should().BeEquivalentTo("list", "enable", "disable");
        Sub("esports").Should().BeEquivalentTo("matches", "results", "events", "rankings", "team", "follow", "unfollow", "subscriptions");
        Sub("esports-admin").Should().BeEquivalentTo("configure", "filters", "roles", "panel", "preview", "pause", "resume", "doctor");
    }

    [Fact]
    public async Task Admin_and_user_commands_are_separated_by_default_member_permissions()
    {
        var (manifest, _) = await BuildAsync();
        const string manageGuild = "32"; // 1 << 5
        foreach (var name in new[] { "setup", "modules", "esports-admin" })
            manifest.Find(name)!.DefaultMemberPermissions.Should().Be(manageGuild, $"/{name} is admin-only");
        foreach (var name in new[] { "help", "bot", "privacy", "esports" })
            manifest.Find(name)!.DefaultMemberPermissions.Should().BeNull($"/{name} is for everyone");
    }

    [Fact]
    public async Task Every_command_is_guild_only_and_has_turkish_descriptions_everywhere()
    {
        var (manifest, _) = await BuildAsync();
        foreach (var command in manifest.Commands)
        {
            command.Contexts.Should().Equal(0);
            command.IntegrationTypes.Should().Equal(0);
            command.DescriptionLocalizations.Should().ContainKey("tr");
            foreach (var option in Flatten(command.Options))
            {
                option.DescriptionLocalizations.Should().ContainKey("tr", $"/{command.Name} … {option.Name}");
                option.Choices.Should().OnlyContain(c => c.NameLocalizations.ContainsKey("tr"));
            }
        }
    }

    [Fact]
    public async Task Autocomplete_is_used_for_teams_tournaments_modules_and_mappings_instead_of_raw_ids()
    {
        var (manifest, _) = await BuildAsync();
        var all = manifest.Commands.SelectMany(c => Flatten(c.Options).Select(o => (Command: c.Name, Option: o))).ToList();
        all.Where(x => x.Option.Type is not (OptionType.SubCommand or OptionType.SubCommandGroup) && x.Option.Name is "team" or "tournament" or "module" or "mapping").Should().OnlyContain(x => x.Option.Autocomplete);
        all.Single(x => x.Command == "esports-admin" && x.Option.Name == "channel").Option.Type.Should().Be(OptionType.Channel);
        all.Single(x => x.Option.Name == "role").Option.Type.Should().Be(OptionType.Role);
    }

    [Fact]
    public async Task Committed_manifest_document_matches_the_code()
    {
        var (manifest, _) = await BuildAsync();
        var path = Path.Combine(RepoRoot(), "docs", "commands.manifest.json");
        File.Exists(path).Should().BeTrue("docs/commands.manifest.json is generated by: commands export --out docs/commands.manifest.json");
        (await File.ReadAllTextAsync(path, TestContext.Current.CancellationToken)).ReplaceLineEndings("\n").Trim().Should().Be(manifest.ToDocumentJson().ReplaceLineEndings("\n").Trim(),
            "regenerate docs/commands.manifest.json after changing commands");
    }

    [Fact]
    public async Task New_module_adds_commands_without_changing_esports_or_core_commands()
    {
        var (without, _) = await BuildAsync(withExample: false);
        var (with, admin) = await BuildAsync(withExample: true);
        CommandManifestValidator.Validate(with, admin).Should().BeEmpty();
        with.Find("example")!.OwnerModule.Should().Be("example");
        foreach (var name in without.Commands.Select(c => c.Name))
            CommandManifest.CanonicalJson(with.Find(name)!, true).Should().Be(CommandManifest.CanonicalJson(without.Find(name)!, true));
    }

    [Fact]
    public void Validator_rejects_bad_names_limits_ordering_and_missing_translations()
    {
        var tr = new Dictionary<string, string> { ["tr"] = "açıklama" };
        ManifestOption Opt(string name, bool required, OptionType type = OptionType.String) =>
            new(type, name, "desc", tr, required, [], [], false, null, null, null, null, []);
        var bad = new ManifestCommand("Bad Name", "", new Dictionary<string, string>(),
            [Opt("optional", false), Opt("required", true)], null, [0, 1], [0], false, "x");
        var tooMany = new ManifestCommand("many", "desc", tr, Enumerable.Range(0, 26).Select(i => Opt($"o{i}", false)).ToList(), null, [0], [0], false, "x");
        var errors = CommandManifestValidator.Validate(new CommandManifest([bad, tooMany], []), new HashSet<string> { "admin" });
        errors.Should().Contain(e => e.Contains("invalid name", StringComparison.Ordinal));
        errors.Should().Contain(e => e.Contains("description length", StringComparison.Ordinal));
        errors.Should().Contain(e => e.Contains("missing 'tr'", StringComparison.Ordinal));
        errors.Should().Contain(e => e.Contains("required options must come before", StringComparison.Ordinal));
        errors.Should().Contain(e => e.Contains("guild-only", StringComparison.Ordinal));
        errors.Should().Contain(e => e.Contains("too many options", StringComparison.Ordinal));
        errors.Should().Contain(e => e.Contains("expected admin command '/admin' is missing", StringComparison.Ordinal));
    }

    // ---- Sync safety (criterion 15) ----

    private static readonly IReadOnlySet<ulong> Allowed = new HashSet<ulong> { 42 };

    private static SyncRequest Request(SyncScope? scope = null, bool prune = false, ulong actualApp = 7, bool allowGlobal = false, IReadOnlySet<string>? admin = null) =>
        new(scope ?? new SyncScope.Guild(42), 7, actualApp, Allowed, allowGlobal, prune, admin ?? new HashSet<string>());

    private static ManifestCommand Cmd(string name, string description = "desc") =>
        new(name, description, new Dictionary<string, string> { ["tr"] = "açıklama" }, [], null, [0], [0], false, "core");

    [Fact]
    public void Empty_manifest_blocks_sync_and_deletes_nothing()
    {
        var plan = CommandSyncPlanner.Plan(new CommandManifest([], []), [new RemoteCommand(1, "help", "{}")], new HashSet<string> { "help" }, Request(prune: true));
        plan.IsBlocked.Should().BeTrue();
        plan.Items.Should().BeEmpty();
    }

    [Fact]
    public void Module_load_error_blocks_sync()
    {
        var plan = CommandSyncPlanner.Plan(new CommandManifest([Cmd("help")], ["esports/EsportsCommands: boom"]), [], new HashSet<string>(), Request());
        plan.IsBlocked.Should().BeTrue();
    }

    [Fact]
    public void Wrong_application_unlisted_guild_and_unapproved_global_are_blocked()
    {
        var manifest = new CommandManifest([Cmd("help")], []);
        CommandSyncPlanner.Plan(manifest, [], new HashSet<string>(), Request(actualApp: 999)).IsBlocked.Should().BeTrue();
        CommandSyncPlanner.Plan(manifest, [], new HashSet<string>(), Request(new SyncScope.Guild(43))).IsBlocked.Should().BeTrue();
        CommandSyncPlanner.Plan(manifest, [], new HashSet<string>(), Request(new SyncScope.Global())).IsBlocked.Should().BeTrue();
        CommandSyncPlanner.Plan(manifest, [], new HashSet<string>(), Request(new SyncScope.Global(), allowGlobal: true)).IsBlocked.Should().BeFalse();
    }

    [Fact]
    public void Diff_creates_updates_keeps_unmanaged_and_prunes_only_managed_with_explicit_flag()
    {
        var help = Cmd("help");
        var manifest = new CommandManifest([help, Cmd("bot", "new description")], []);
        var remote = new List<RemoteCommand>
        {
            new(1, "help", CommandManifest.CanonicalJson(help, includeGlobalOnlyFields: false)),
            new(2, "bot", CommandManifest.CanonicalJson(Cmd("bot", "old description"), false)),
            new(3, "legacy", "{}"),
            new(4, "someone-elses", "{}"),
        };
        var managed = new HashSet<string> { "help", "bot", "legacy" };

        var dry = CommandSyncPlanner.Plan(manifest, remote, managed, Request());
        dry.Items.Should().BeEquivalentTo(new[]
        {
            new SyncPlanItem(SyncAction.Unchanged, "help", 1),
            new SyncPlanItem(SyncAction.Update, "bot", 2),
            new SyncPlanItem(SyncAction.KeepManagedNotInManifest, "legacy", 3),
            new SyncPlanItem(SyncAction.KeepUnmanaged, "someone-elses", 4),
        });

        var prune = CommandSyncPlanner.Plan(manifest, remote, managed, Request(prune: true));
        prune.Items.Should().Contain(new SyncPlanItem(SyncAction.DeleteManaged, "legacy", 3));
        prune.Items.Should().Contain(new SyncPlanItem(SyncAction.KeepUnmanaged, "someone-elses", 4));
    }

    [Fact]
    public async Task Sync_service_never_touches_remote_state_when_the_manifest_is_invalid()
    {
        var registrar = new RecordingRegistrar();
        await using var host = await TestHost.CreateAsync();
        await using var scope = host.Scope();
        var service = scope.ServiceProvider.GetRequiredService<CommandSyncService>();
        var report = await service.RunAsync(new CommandManifest([], []), registrar, Request(), apply: true, CancellationToken.None);
        report.Applied.Should().BeFalse();
        registrar.Calls.Should().Equal("app");
    }

    [Fact]
    public async Task Sync_service_dry_run_changes_nothing_and_apply_records_managed_commands()
    {
        var registrar = new RecordingRegistrar();
        await using var host = await TestHost.CreateAsync();
        await using var scope = host.Scope();
        var service = scope.ServiceProvider.GetRequiredService<CommandSyncService>();
        var manifest = new CommandManifest([Cmd("help")], []);

        var dry = await service.RunAsync(manifest, registrar, Request(), apply: false, CancellationToken.None);
        dry.Plan.Items.Should().ContainSingle(i => i.Action == SyncAction.Create);
        registrar.Calls.Should().NotContain(c => c.StartsWith("upsert", StringComparison.Ordinal));

        var applied = await service.RunAsync(manifest, registrar, Request(), apply: true, CancellationToken.None);
        applied.Performed.Should().ContainSingle();
        registrar.Calls.Should().Contain("upsert help");
    }

    private sealed class RecordingRegistrar : ICommandRegistrar
    {
        public List<string> Calls { get; } = [];

        public Task<ulong> GetApplicationIdAsync(CancellationToken cancellationToken)
        {
            Calls.Add("app");
            return Task.FromResult(7UL);
        }

        public Task<IReadOnlyList<RemoteCommand>> GetCommandsAsync(SyncScope scope, CancellationToken cancellationToken)
        {
            Calls.Add("list");
            return Task.FromResult<IReadOnlyList<RemoteCommand>>([]);
        }

        public Task<ulong> UpsertAsync(SyncScope scope, ManifestCommand command, CancellationToken cancellationToken)
        {
            Calls.Add("upsert " + command.Name);
            return Task.FromResult(100UL);
        }

        public Task DeleteAsync(SyncScope scope, ulong commandId, CancellationToken cancellationToken)
        {
            Calls.Add("delete " + commandId);
            return Task.CompletedTask;
        }
    }

    private static IEnumerable<ManifestOption> Flatten(IEnumerable<ManifestOption> options) =>
        options.SelectMany(o => new[] { o }.Concat(Flatten(o.Options)));

    internal static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "ToroSquad.slnx")))
            dir = dir.Parent;
        return dir?.FullName ?? throw new InvalidOperationException("repo root not found");
    }
}
