// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToroSquad.Infrastructure.Persistence;

#nullable disable

namespace ToroSquad.Bot.Migrations
{
    [DbContext(typeof(ToroDbContext))]
    partial class ToroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ToroSquad.Infrastructure.Persistence.ConfirmationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("confirmation", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Infrastructure.Persistence.GuildModuleStateEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("ChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChangedBy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "ModuleId");

                    b.ToTable("guild_module_state", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Infrastructure.Persistence.GuildPresenceEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeftAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PurgedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("guild_presence", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Infrastructure.Persistence.GuildSettingsEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SetupCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("guild_settings", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Infrastructure.Persistence.ManagedCommandEntity", b =>
                {
                    b.Property<long>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SyncedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId", "Scope", "Name");

                    b.ToTable("managed_command", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Infrastructure.Persistence.OutboxMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveredFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveredPayloadHash")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EditAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EditPending")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReconcileAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SentAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogicalKey")
                        .IsUnique();

                    b.HasIndex("GuildId", "ModuleId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Esports.Persistence.EsportsFilterEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dimension")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Dimension", "Value")
                        .IsUnique();

                    b.ToTable("esports_filter", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Esports.Persistence.EsportsGuildConfigEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelProblem")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ChannelProblemAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyReminders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyResults")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReminderLeadMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SpoilerMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VrsTopN")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WatermarkUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("esports_guild_config", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Esports.Persistence.KnownTeamEntity", b =>
                {
                    b.Property<string>("TeamKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TeamKey");

                    b.ToTable("esports_known_team", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Esports.Persistence.MatchSnapshotEntity", b =>
                {
                    b.Property<string>("MatchKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CancelledObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PostponedObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PreviousStartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RescheduledObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RescheduledToUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScheduledStartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchKey");

                    b.HasIndex("ScheduledStartUtc");

                    b.ToTable("esports_match_snapshot", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Esports.Persistence.ProviderStateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastDetail")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSuccessAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextAllowedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("esports_provider_state", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Esports.Persistence.RoleGrantEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GrantedByBot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HadRoleBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "UserId", "RoleId");

                    b.ToTable("esports_role_grant", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Esports.Persistence.RoleMappingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PingOnReminder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PingOnResult")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SelfService")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SelfServiceApprovedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SelfServiceApprovedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "RoleId", "TeamKey")
                        .IsUnique();

                    b.ToTable("esports_role_mapping", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Esports.Persistence.TeamFollowEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "TeamKey");

                    b.HasIndex("GuildId", "UserId", "TeamKey")
                        .IsUnique();

                    b.ToTable("esports_team_follow", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Esports.Persistence.UserPreferenceEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideResults")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("esports_user_pref", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Formula1.Persistence.F1ProviderStateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastDetail")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSuccessAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("f1_provider_state", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Formula1.Persistence.F1ResultSnapshotEntity", b =>
                {
                    b.Property<string>("SessionKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Corrections")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FetchedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstAvailableAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastChangedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionKey");

                    b.ToTable("f1_result_snapshot", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Formula1.Persistence.F1SessionSnapshotEntity", b =>
                {
                    b.Property<string>("SessionKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CancelledObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinalisedObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLifecycleEventAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LifecycleProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LifecycleProviderRef")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultLastDetail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResultNextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultsProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultsProviderRef")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScheduledEndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScheduledStartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StandingsAttachedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandingsBaselineConstructorsHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StandingsBaselineDriversHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("StandingsChecks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StandingsConstructorsSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StandingsDriversSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StandingsNextCheckAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StandingsWatchUntil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StandingsWindowClosed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedRecordedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SuspendedObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionKey");

                    b.HasIndex("ScheduledStartUtc");

                    b.HasIndex("LifecycleProvider", "LifecycleProviderRef");

                    b.HasIndex("Season", "Round");

                    b.ToTable("f1_session_snapshot", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Formula1.Persistence.F1StandingsSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("FetchedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastConfirmedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Season", "Id");

                    b.ToTable("f1_standings_snapshot", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Formula1.Persistence.Formula1GuildConfigEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelProblem")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ChannelProblemAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyPracticeResults")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyPracticeStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyQualifyingResults")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyQualifyingStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyRaceResults")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyRaceStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifySprintQualifyingResults")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifySprintQualifyingStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifySprintResults")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifySprintStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyStandings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paused")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PingOnResults")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PingOnStarts")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PingRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SpoilerMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WatermarkUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("f1_guild_config", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Volleyball.Persistence.VbMatchSnapshotEntity", b =>
                {
                    b.Property<string>("MatchKey")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayLogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("AwaySets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BroadcastsJson")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompetitionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompetitionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentSet")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentSetAwayPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentSetHomePoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Finished")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowedSide")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeLogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeSets")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastListedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastProblem")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastProblemAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastProviderUpdateAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingJson")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Postponed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Problems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderMatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Round")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetsJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Started")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MatchKey");

                    b.HasIndex("StartTimeUtc");

                    b.HasIndex("Provider", "ProviderMatchId")
                        .IsUnique();

                    b.ToTable("vb_match_snapshot", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Volleyball.Persistence.VbProviderStateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastDetail")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSuccessAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("vb_provider_state", (string)null);
                });

            modelBuilder.Entity("ToroSquad.Modules.Volleyball.Persistence.VolleyballGuildConfigEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelProblem")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ChannelProblemAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyFinal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyPostponedCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyReminder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifySets")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyStarted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paused")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PingOnFinal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PingOnReminder")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PingRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WatermarkUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("vb_guild_config", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
